"""CONTRACT 2, the artifact. The compact schedule trace the web replays.

Its shape is mirrored by ``frontend/src/lib/contract.types.ts`` so a drift fails the web build. The
schema id is versioned and every consumer checks it.

Two sizes of trace, and the difference is a licence, not an engineering choice:

- **Synthetic twins** commit the FULL ``periodOfBlock`` array. They are generated here and are
  license-free, so the browser can replay the pit bench by bench, block by block.
- **MineLib cases** commit AGGREGATES ONLY. The instances are downloaded under an academic-download
  grant that does not permit redistribution, so a per-block MineLib schedule never enters this repo.
  The published-instance case therefore shows charts and numbers, not a 3D replay, and the app says
  which and why rather than quietly showing a different deposit.
"""

from __future__ import annotations

from typing import Any

import numpy as np

TRACE_SCHEMA = "phaseflow.schedule-trace/v1"


def _round(a: np.ndarray | list, nd: int = 4) -> list:
    return [round(float(v), nd) for v in np.asarray(a).ravel()]


def build_trace(
    *,
    case: Any,
    instance: Any,
    results: list[Any],
    controls: dict,
    published: dict,
) -> dict:
    """Assemble the committed artifact for one case, over every method that ran on it."""
    cpit = instance.cpit
    synthetic = bool(instance.synthetic)

    methods = []
    for r in results:
        row = {
            "method": r.method,
            "rung": r.rung,
            "heuristic": r.heuristic,
            "npv": round(r.npv, 2),
            "bound": round(r.bound, 2),
            "gapPct": round(r.gap_pct, 4),
            "runtimeMs": round(r.runtime_ms, 1),
            "minedBlocks": r.mined_blocks,
            "notes": r.notes,
            "periods": [
                {
                    "t": p.t,
                    "minedTonnes": round(p.mined_tonnes, 1),
                    "oreTonnes": round(p.ore_tonnes, 1),
                    "wasteTonnes": round(p.waste_tonnes, 1),
                    "headGrade": round(p.head_grade, 6),
                    "metal": round(p.metal, 2),
                    "value": round(p.value, 2),
                    "discCashFlow": round(p.disc_cash_flow, 2),
                    "cumNpv": round(p.cum_npv, 2),
                    "stripRatio": round(p.strip_ratio, 4),
                    "resourceUse": _round(p.resource_use, 1),
                    "resourceLimit": _round(p.resource_limit, 1),
                    "components": p.components,
                    "largestComponentShare": round(p.largest_component_share, 4),
                    "minWidthBlocks": p.min_width_blocks,
                    "blocks": p.blocks,
                }
                for p in r.periods
            ],
        }
        if synthetic:
            row["periodOfBlock"] = [int(v) for v in r.period_of_block]
        methods.append(row)

    trace: dict[str, Any] = {
        "schema": TRACE_SCHEMA,
        "caseId": case.id,
        "category": case.category,
        "title": {"en": case.title_en, "es": case.title_es},
        "role": {"en": case.role_en, "es": case.role_es},
        "instance": {
            "source": "twin" if synthetic else "minelib",
            "synthetic": synthetic,
            "nBlocks": instance.n_blocks,
            "nPrecedenceArcs": int(instance.precedence.n_arcs),
            "dims": list(instance.dims),
            "upitValue": round(instance.upit_value, 2),
            "upitBlocks": int(instance.upit_in_pit.sum()),
            "licence": (
                "synthetic, generated by oreblocks, free to redistribute"
                if synthetic
                else "MineLib, academic download only; aggregate results committed, never per-block data"
            ),
        },
        "scenario": {
            "periods": cpit.n_periods,
            "discountRate": cpit.discount_rate,
            "periodOneUndiscounted": cpit.period_one_undiscounted,
            "declared": not bool(published),
            "resources": [
                {
                    "id": i,
                    "name": (cpit.resource_names[i] if i < len(cpit.resource_names) else f"r{i}"),
                    "limitPerPeriod": _round(cpit.limit[i], 1),
                }
                for i in range(cpit.n_resources)
            ],
        },
        "published": published,
        "controls": controls,
        "contract": {
            "accepted": instance.report.ok,
            "flags": instance.report.flagged,
            "facts": instance.report.facts,
        },
        "methods": methods,
    }

    if synthetic:
        trace["blocks"] = {
            "x": [int(v) for v in instance.x],
            "y": [int(v) for v in instance.y],
            "level": [int(v) for v in instance.level],
            "grade": _round(instance.grade, 5),
            "tonnage": _round(instance.tonnage, 1),
            "value": _round(instance.cpit.value, 1),
            "inPit": [int(v) for v in instance.upit_in_pit],
        }
    return trace
